site_name: Template::HAML
site_url: https://gdonald.github.io/Template-HAML/
repo_url: https://github.com/gdonald/Template-HAML
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Syntax:
    - Tags: syntax/tags.md
    - Attributes: syntax/attributes.md
    - Indentation: syntax/indentation.md
    - Doctype: syntax/doctype.md
    - Comments: syntax/comments.md
    - Embedded code: syntax/embedded-code.md
    - Plain text: syntax/plain-text.md
    - Control flow: syntax/control-flow.md
    - Filters: syntax/filters.md
    - Whitespace: syntax/whitespace.md
    - Helpers: syntax/helpers.md
    - Layouts and partials: syntax/layouts-partials.md
    - Configuration: syntax/config.md
  - API: api.md
  - CLI: cli.md
  - Tests: testing.md
theme:
  name: 'material'
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
