name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        raku-version: ['latest']
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Raku version
        run: raku --version
      - name: Install dependencies
        run: zef install --deps-only --/test --test-depends .
      - name: Run tests
        run: zef test .
